services:
  backend-soundcloud:
    container_name: soundcloud-spring
    build:
      context: ./backend-spring/soundcloud
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8081
      SOUNDCLOUD_MONGO_URI: ${MONGO_URI}
      SOUNDCLOUD_UPLOAD_UPLOAD_FILE_BASE_URI: file:///uploads/
      SOUNDCLOUD_UPLOAD_UPLOAD_FILE_PATH: /uploads/
      SOUNDCLOUD_TRACK_HSL: /track_hsl/
    volumes:
      - ./sample-data/upload-docker/:/uploads/
      - ./sample-data/track_hsl-docker/:/track_hsl/
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s
    networks:
      - soundcloud-network

  frontend-soundcloud:
    container_name: soundcloud-nextjs
    build:
      context: ./frontend-nextjs/user-nextjs-mui-soundcloud
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://backend-soundcloud:8081
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXTAUTH_URL: http://192.168.1.216:3000
    restart: unless-stopped
    depends_on:
      backend-soundcloud:
        condition: service_healthy
    networks:
      - soundcloud-network

  nginx:
    image: nginx:1.28.0
    container_name: nginx-soundcloud
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80 # port: 3000 for NEXTAUTH_URL
    depends_on:
      frontend-soundcloud:
        condition: service_started
    networks:
      - soundcloud-network

networks:
  soundcloud-network:
    driver: bridge

#docker compose -p devtaycode-soundcloud-fullstack up -d
