services:
  db-mymongo:
    image: mongo:8.0.11
    container_name: db_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"

  backend-spring:
    container_name: backend_spring
    build:
      context: ./soundcloud
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      SOUNDCLOUD_MONGO_URI: mongodb://root:123456@db-mymongo:27017
      SOUNDCLOUD_UPLOAD_UPLOAD_FILE_BASE_URI: file:///uploads/
    depends_on:
      - db-mymongo
    volumes:
      - ./upload-docker/:/uploads/
    ports:
      - 8080:8080
    # docker compose -p devtaycode-soundcloud up -d

volumes:
  mongo_data:
