services:
  nginx:
    image: nginx:1.23
    container_name: nginx-soundcloud
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80 # port: 3000 for NEXTAUTH_URL

  backend-soundcloud:
    # run this first because use SSG
    image: thachvabach2/devtaycode-backend-soundcloud-spring:1.2
    container_name: backend-soundcloud-spring
    environment:
      SERVER_PORT: 8081
      SOUNDCLOUD_MONGO_URI: mongodb+srv://ngocbach12a1:VXL2QqwQcpRSIrzX@cluster0.qfttq.mongodb.net/
      SOUNDCLOUD_DELAY_TIMEOUT: 0
      SOUNDCLOUD_UPLOAD_UPLOAD_FILE_BASE_URI: file:///uploads/
    volumes:
      - ./upload-docker/:/uploads/
    ports:
      - 8081:8081

  frontend-nextjs:
    container_name: frontend-soundcloud-nextjs
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped

#docker compose -p devtaycode-soundcloud-fullstack up -d
